name: Sync sitemaps once a day

on:
  schedule:
    - cron: "0 */24 * * *"
  workflow_dispatch:

jobs:
  sync_sitemaps:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install modules
        run: yarn --ignore-engines

      - name: Run sync_sitemaps.js
        env:
          UPSTASH_REDIS_URL: ${{ secrets.UPSTASH_REDIS_URL }}
          UPSTASH_REDIS_TOKEN: ${{ secrets.UPSTASH_REDIS_TOKEN }}
        run: node scripts/sync_sitemaps.js.js
