name: CI
on: push
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn --ignore-engines
      - name: Run tests
        run: yarn test:ci
