name: Hourly cron job
on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Cleanup weekly pass for users
        id: cleanupWeekly
        uses: fjogeleit/http-request-action@master
        with:
          url: "https://www.dca-cc.com/api/billing/cleanup"
          method: "POST"
          bearerToken: "${{ secrets.ACTION_KEY }}"
